version = 1

; (Optional) This section provides global settings shared across all presets.
; If the same key is defined in a specific preset, it will override the value in this global section.
[*]
mmap = false
ctx-size = 8192
reasoning = off
flash-attn = on 
temperature = 0
#grammar-file = ..\gguf_models\en_ru.gbnf
parallel = 1
#ngl = 1
#batch-size = 512
; If the key corresponds to an existing model on the server,
; this will be used as the default config for that model
#load-on-startup = ..\gguf_models\en_ru.gbnf

# comma-separated list of devices to use for offloading (none = don't offload)
# it helps to bypass ErrorOutOfDeviceMemory
dev = none #Vulkan0 #none
#forces use of cache, prevents network access
offline = true

[unsloth/Qwen3-14B]
model = ..\gguf_models\Qwen3-14B-Q4_K_M.gguf
chat-template=chatml # llamacpp uses chat template from gguf model, but just in case.
#hf-repo = unsloth/Qwen3-14B-GGUF:Q4_K_M
#alias = textgen-model_14b
port = 8010

[unsloth/Qwen3-14B_16c]
model = ..\gguf_models\Qwen3-14B-Q4_K_M.gguf
#hf-repo = unsloth/Qwen3-14B-GGUF:Q4_K_M
#alias = textgen-model_14b
ctx-size = 16384

[Qwen/Qwen3-Embedding-4B-GGUF]
model = ..\gguf_models\Qwen3-Embedding-4B-Q4_K_M.gguf
#hf-repo = Qwen/Qwen3-Embedding-4B-GGUF:Q4_K_M
alias = embedding-model
port = 8011
ctx-size = 512
embeddings = true
pooling = mean       # Average all token embeddings. Standard for embedding models (Qwen3-Embedding).

[Voodisss/Qwen3-Reranker-4B-GGUF-llama_cpp]
model = ..\gguf_models\Qwen3-Reranker-4B-Q4_K_M.gguf
#hf-repo = Voodisss/Qwen3-Reranker-4B-GGUF-llama_cpp:Q4_K_M
alias = reranker-model
port = 8012
#reranking -- Shortcut that enables both embedding = true and pooling = rank in one flag.
reranking = true    # Enables the /v1/rerank endpoint for this model
pooling = rank      # Sets LLAMA_POOLING_TYPE_RANK (required for classifier output)
embedding = true    # Enables embedding extraction (reranking needs this internally)

[unsloth/Qwen3-VL-8B-Instruct-GGUF]
model = ..\gguf_models\Qwen3-VL-8B-Instruct-Q4_K_M.gguf

[unsloth/Qwen3.5-9B-GGUF]
model = ..\gguf_models\Qwen3.5-9B-Q4_K_M.gguf

[Nanbeige.Nanbeige4.1-3B]
model = ..\gguf_models\Nanbeige.Nanbeige4.1-3B.Q4_K_M.gguf

[gemma-4-E4B-it]
model = ..\gguf_models\gemma-4-E4B-it-Q4_K_M.gguf

[gemma-3-12b-it-qat]
model = ..\gguf_models\gemma-3-12b-it-qat-Q4_K_M.gguf

[Ministral-3-14B-Instruct-2512]
model = ..\gguf_models\Ministral-3-14B-Instruct-2512-Q4_K_M.gguf

[granite-4.0-h-tiny]
model = ..\gguf_models\granite-4.0-h-tiny-Q4_K_M.gguf

[Phi-4-reasoning-plus-Q4_K_M]
model = ..\gguf_models\Phi-4-reasoning-plus-Q4_K_M.gguf

[Qwen2.5-VL-7B-Instruct-Q4_K_M]
model = ..\gguf_models\Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf

[DeepSeek-R1-Distill-Qwen-14B-Q4_K_M]
model = ..\gguf_models\DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf

[Qwopus3.5-9B-v3.Q4_K_M]
model = ..\gguf_models\Qwopus3.5-9B-v3.Q4_K_M.gguf

[Qwen3-8B-Q4_K_M]
model = ..\gguf_models\Qwen3-8B-Q4_K_M.gguf

[Qwopus-GLM-18B-Healed-Q4_K_M]
model = ..\gguf_models\Qwopus-GLM-18B-Healed-Q4_K_M.gguf

[Meta-Llama-3.1-8B-Instruct]
model = ..\gguf_models\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf

[gemma-2-9b-it]
model = ..\gguf_models\gemma-2-9b-it-Q4_K_M.gguf

[medgemma-4b-it-Q4_K_M]
model = ..\gguf_models\medgemma-4b-it-Q4_K_M.gguf

[translategemma-12b-it-Q4_K_M]
model = ..\gguf_models\translategemma-12b-it-Q4_K_M.gguf

[dnotitia_Smoothie-Qwen3-14B_Q4_K_M]
model = ..\gguf_models\dnotitia_Smoothie-Qwen3-14B_Q4_K_M.gguf

; If the key does NOT correspond to an existing model,
; you need to specify at least the model path or HF repo
[custom_model]
model = /Users/abc/my-awesome-model-Q4_K_M.gguf













